### ISSUE TITLE
Help / Feature Request: Hide "Commit" and "Compare Commit" views

### ISSUE THREAD

**Issue by TedDriggs** [DonJayamanne/gitHistoryVSCode#150]
v0.2.3 added the ability to view commit information in the Explorer view. I'd prefer not to see this, but there doesn't appear to be any way to disable Explorer views. Is it possible for this to be an extension setting, or does this need to be something offered by the editor itself?

**Comment by DonJayamanne** [comment]
Yes will include a song to hide them asap

**Comment by DonJayamanne** [comment]
Agreed they can be annoying

**Comment by ajaygm** [comment]
I agree with @TedDriggs ... I like my Explorer to have nothing more that what it currently has.

I was also thinking if the right place to have these views could be the "Source Control" sidebar instead of "Explorer". 

Can we think of some other GUI option, may be extending the HTML that is being produced currently to have some left pane which is dynamically shown when you select the compare option.

Looking at this code...
` vscode.commands.executeCommand('vscode.previewHtml', previewUri, vscode.ViewColumn.One, title) `

Can `vscode.ViewColumn.One` option be used?

Don't have a very firm opinion of any of these options, but just throwing in some ideas.

**Comment by icetbr** [comment]
VSCode added this feature in this months update (08/2017). Just right click and remove it

**Comment by renanveroneze** [comment]
It would be interesting to have the option to keep hidden, even in new windows.
