### ISSUE TITLE
Avatar not showing please advice

### ISSUE THREAD

**Issue by caiceA** [DonJayamanne/gitHistoryVSCode#262]
<img width="331" alt="screen shot 2018-04-23 at 23 59 09" src="https://user-images.githubusercontent.com/16766231/39155442-5ec3f4a6-4752-11e8-8314-ca6b56ada3c9.png">

**Comment by caiceA** [comment]
@DonJayamanne  ok ok no problem i wait for new option actually i love this plugin so i just want this to be perfect always 😃

**Comment by DonJayamanne** [comment]
Apologies for the delay, please could you open the `console window` and check if there are any errors.
Or please could you point me to the repo for me to try this out my self.

**Comment by DonJayamanne** [comment]
Please go into `help->Toggle developer tools` to get to the `console window`

**Comment by DonJayamanne** [comment]
Please could you send the URL to this repo?

**Comment by caiceA** [comment]
its actually private Repo but its not about this one if you look at the top first img it has another repo i have 4 repos all have the same 
Just a quick question is there any way i hide the avatar mistakenly in the VS code? or its something related development issue

**Comment by caiceA** [comment]
Please see this https://github.com/caiceA/upnorway.git

**Comment by DonJayamanne** [comment]
Unfortunately it won't work for you as there's no way to determine whether the fetched github avatars belong to you.
Currently the extension queries github api to get a list of users with the same name and login, but when we get the list the email address is missing (this is because you have not made this public). Hence theres no way to match (confirm) the results.
Unless you expose your email it will not appear.
FYI - your email address is visible in the commits (if you really want to hide your email addresses, you'd want to hide that too). Check the following link https://saraford.net/2017/02/19/how-to-hide-your-email-address-in-your-git-commits-but-still-get-contributions-to-show-up-on-your-github-profile-050/

**Comment by JWleo** [comment]
just the same with you,i also can't see my github-Avatar

**Comment by DonJayamanne** [comment]
@JWleo In your case, I've found a bug in the code. Will fix that.
