### ISSUE TITLE
Can't view my photo in git history

### ISSUE THREAD

**Issue by akashagarwal7** [DonJayamanne/gitHistoryVSCode#349]
I can see the photo of other people but not mine. The other person can't view my image either. Is this a known bug in the app or something I need to fix on GitHub?

**Comment by ole1986** [comment]
It is same for me...

In some cases it seem to gather the wrong user from github, by taking the name instead of using the exact match (the user name itself)

I will have a closer look into it..
Thank you for reporting

**Comment by ole1986** [comment]
The common reason why some avatar images are not properly displayed or showing the wrong image (see #287) is that the github API does not support a request based on the user login OR user name (full-style) to match the exact user defined in the commit.

Roughly the logic covers the below steps and is located [here](https://github.com/DonJayamanne/gitHistoryVSCode/blob/master/src/adapter/avatar/github.ts):

1. Find the exact match base on commit author using Github API request [/users/&lt;author name&gt;](https://api.github.com/users/ole1986)
2. If no match found, try to search the author name using Github API request [search/users?q=&lt;author name&gt;](https://api.github.com/search/users?q=ole)
3. Compare the email addresses from the results of 2. (if public) against the the authors email to find a match.
4. Otherwise, no match

Hope I did not missed any important part.

As you may already recognize, these four steps can cause false-positive results of a different user avatar (especially when no public email is defined on github).

**Unless we cannot search for the name of a user through the Github API my suggestion is  to only search on exact matches (in this case the user login).**

@DonJayamanne do you agree to this? Or any other hints?

**Comment by ole1986** [comment]
In addition to my previous post I am also planning to add a new extension setting allowing to manage the avatar cache expiration or completely disable it. See screenshot below

![githistory-avatar-cache-setting](https://user-images.githubusercontent.com/4850116/52772511-f3e9d300-3038-11e9-8d6a-0aa3729f9447.png)

**Comment by cristianmtr** [comment]
Has this been fixed? I am also seeing some other photo in the history. I would like to simply remove it completely, if possible

**Comment by ole1986** [comment]
It should be fixed in version 0.4.7 which is not yet released.
@DonJayamanne any news on when to release the version?
