### ISSUE TITLE
Repository Pick with Workingtree

### ISSUE THREAD

**Issue by RomanBadiornyi** [DonJayamanne/gitHistoryVSCode#445]
Hi

I'm using 0.5.3 version of extension.
I have single repository, but I'm using a working tree with 3 different folders (which points to different branches). 
In this situation repository picker isn't shown and it does not allow to choose at which folder I want to check git history, instead it does open first (or maybe even random) folder history.

**Comment by ole1986** [comment]
Since version 0.5.X the Git History extension is using the vscode git extension api to read repositories.

Please make sure the vscode source control has listed (and opened) your repos.

![image](https://user-images.githubusercontent.com/4850116/75042456-b7a84880-54be-11ea-8a7a-6c23c9fa8ca2.png)

To open another repository you may need to select it first from the source controll provider list.

**Comment by RomanBadiornyi** [comment]
Indeed it works, So the selected repository gets opened. 
P.S. Maybe it still will be useful to have separate command to force repository picker to be displayed, so that it's possible to open selected repository using key bindings without moving and selecting the required repo. 
Thank you for clarification!
