### ISSUE TITLE
Suggestion for CI/CD improvements?

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/gitHistoryVSCode#456]
@ole1986 can you think of any?

**Comment by ole1986** [comment]
Since we are already using GitHub actions to automate deployments I assume this issue is more focused on CI.

But honestly I do not know much what would be the best for such project.

Of course we should at least get the unit test probably working (#325 ).

Also is there a chance to apply code formatters on every PR being merged into master branch?

**Comment by DonJayamanne** [comment]
Great, all have been addressed, we issues issues for formatting and testing.
Thanks
