### ISSUE TITLE
Better error handling for long filenames

### ISSUE THREAD

**Issue by luckskjedi** [DonJayamanne/gitHistoryVSCode#47]
Error node Git LOG! 

![image](https://cloud.githubusercontent.com/assets/2601264/19077764/3985e01a-8a24-11e6-884b-fc08cfff3882.png)

**Comment by mikes-gh** [comment]
Are you working on a clone of this repo?

**Comment by oolleegg55** [comment]
I have the same problem. But the error occurs from the deleted folder already. Once I accidentally pushed the folder "node_modules" to repo. The "node_modules" was made by old version of the NPM, that's why the paths had such long names.
And now I don't know what to do. I think this extension cannot work with my repo.

**Comment by mikes-gh** [comment]
If you cloned this repo node_modules should already be be in gitignore.

To reset you node modules you could

- make sure node_modules in gitignore

- Remove node_modules from the repo you accidently added
`git rm -r --cached node_modules`

- Do an npm install using new version of node (without long path issue
`rm -Rf node_modules`
`npm install`

**Comment by mikes-gh** [comment]
Just so I understand are you developing this extension?
If you just need to use this extension do an ext install.

**Comment by oolleegg55** [comment]
@mikes-gh thank you very much! Yes, I can remove it from the old commits, really. I will do it later, when I read about it attentively. My repo is very sensitive and old.

> Just so I understand are you developing this extension?

No, I've spoken about mine.

**Comment by mikes-gh** [comment]
Ok Im getting the picture now :smile: 

So you have some long paths in a commit from old version of node?

I see your issue now.
And of course you cant easily delete the commit.

But most developers won't have this issue since they will

- Not have node_modules in their repo.
- Be using a newer version of node that flattens the paths.

I am going to commit a file with a very long path on linux and see if I can repro.
On windows you wont be able to access the file anyway so probably best to just show path too long.
On linux to be correct we should be able to access the file.

I'll look into it.

**Comment by mikes-gh** [comment]
Can you clone your repo so you are safe and find out if

`git rm -r --cached node_modules`

resolves this issue

**Comment by oolleegg55** [comment]
> So you have some long paths in a commit from old version of node?

Yes, exactly.

> But most developers won't have this issue since they will
> Not have node_modules in their repo.
> Be using a newer version of node that flattens the paths.

I think so too.

> Can you clone your repo so you are safe and find out if
> git rm -r --cached node_modules
> resolves this issue

Exactly this command is not for my case. I have not this folder already. I have to use such approach: https://help.github.com/articles/remove-sensitive-data/

To check the current problem I cloned my repo with some depth witch doesn't have the folder "node_modules"(I still couldn't remove node_modules from it). And now this problem disappeared. It means your suggestion about old version NPM in a repo is right.

**Comment by mikes-gh** [comment]
> Can you clone your repo so you are safe and find out if
git rm -r --cached node_modules
resolves this issue
> Exactly this command is not for my case. I have no this folder already. I have to use such approach: https://help.github.com/articles/remove-sensitive-data/
 
This doesn't remove the file in your working folder but from the repo itself.

Did you try it?

**Comment by oolleegg55** [comment]
> This doesn't remove the file in your working folder but from the repo itself.

It is what I need.

> Did you try it?

Yes, I did. When I was writing the previous message deleting was in process. It took long time for me.
But now I haven't "node_modules" in my repo and have no error. 
Extensions is working good.

**Comment by mikes-gh** [comment]
Putting in backlog for now.

**Comment by DonJayamanne** [comment]
Closing for now, until reported again
