### ISSUE TITLE
Git History (git log) Does Not Render Correctly with Non-Default Window Zoom

### ISSUE THREAD

**Issue by nfantis** [DonJayamanne/gitHistoryVSCode#52]
If a non-default zoom level is used in settings.json, the Git History (git log) does not render the hash button and details correctly.

-- Default Zoom Level
![image](https://cloud.githubusercontent.com/assets/22967457/19577031/7e73b15e-96e3-11e6-88bf-ce096a844a3f.png)

-- window.zoomLevel: -0.4: Notice the hash is cut off and, if the zoom level were even lower (i.e. -1), the bottom details box will not appear.
![image](https://cloud.githubusercontent.com/assets/22967457/19577096/b8ca165e-96e3-11e6-84ae-fbe420dd9fb7.png)

**Comment by kumarharsh** [comment]
I've also noticed this. I'll have a look.

**Comment by kumarharsh** [comment]
@nfantis This seems to be a bug in vscode itself. It expands/shrinks the view area by an indeterminate amount when the zoom is set. I don't think anything can be done here. Referring this to @DonJayamanne.

**Comment by nfantis** [comment]
@kumarharsh Thanks for looking into this, I really appreciate it.  Love the extension!

**Comment by DonJayamanne** [comment]
Thanks Kumar

**Comment by kumarharsh** [comment]
You're welcome! I actually had a similar problem earlier, and one of the vscode's core team members said that they'd prefer [people *not* use `window.zoomLevel` at all](https://github.com/Microsoft/vscode/issues/10993#issuecomment-242758853.). It's kind of an electron problem, and it's gonna be hard to fix some of the issues surrounding zoomLevel without involvement of more parties. Although it does seem weird that vscode messes up it's div sizes so badly due to this, but atleast the core team is [aware of this bug](https://github.com/Microsoft/vscode/issues/5745).
