### ISSUE TITLE
History is reversed

### ISSUE THREAD

**Issue by Xiot** [DonJayamanne/gitHistoryVSCode#8]
When viewing the file history, to diff seems reversed from what I would expect.

It shows
[current file] -> [old version]
which shows how to get the current version back to the version in the specified commit.

I was originally expecting
[old version] -> [current file] 
which should show what changes have been made since the previous commit

**Comment by DonJayamanne** [comment]
Fixed in latest version

**Comment by siddharth-krishna** [comment]
I think this may be happening again. I'm opening a file, running command `Git: View File History`, choosing a commit, and then selecting `Compare against workspace file`. I see the current version of the file on the left and the old version of the file on the right. So things I've added are highlighted in red, instead of green.

Git History version: 0.1.0
VS Code version: 1.5.3

**Comment by mikes-gh** [comment]
I confirm this is happening to me also.
This is a major bug in my opinion with no workaround.
I will see if I can debug it and post back here.

**Comment by DonJayamanne** [comment]
Thanks for your help on this guys

**Comment by wkema** [comment]
It seems this happened again. After choosing a commit and selecting compare against workspace version, I can see the workspace file is on the left, which is not editable, while the commit is on the right.

Git History version: 0.4.0
vscode version: 1.20.1
